apps/seguros/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import Inicio, LicitacionDetailView, LicitacionesListView, AprobadasListView, AprobadaDetailView, AprobadaUpdateView, EnviadaListView, EnviadaDetailView, EnviadaUpdateView, LicitacionCreateView, LicitacionUpdateView, LicitacionDeleteView, ListasEnviarListView, ListasEnviarView, ListaEnviarDetailView, PreparadasListView, PreparadaDetailView, PreparadaUpdateView, ObtenerPeritosView, TerminadaListView, TerminadaDetailView

app_name = 'apps.seguros'

urlpatterns = [

    path(
        route='',
        view=login_required(Inicio.as_view()),
        name='inicio'
    ),

    path(
        route='licitaciones/',
        view=login_required(LicitacionesListView.as_view()),
        name='listar_licitaciones'
    ),

    path(
        route='crear_licitacion/',
        view=login_required(LicitacionCreateView.as_view()),
        name='crear_licitacion'
    ),

    path(
        route='detalle_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDetailView.as_view()),
        name='detalle_licitacion'
    ),

    path(
        route='editar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionUpdateView.as_view()),
        name='editar_licitacion'
    ),

    path(
        route='eliminar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDeleteView.as_view()),
        name='eliminar_licitacion'
    ),

    path(
        route='aprobadas/',
        view=login_required(AprobadasListView.as_view()),
        name='listar_aprobadas'
    ),

    path(
        route='detalle_aprobada/<uuid:pk>/',
        view=login_required(AprobadaDetailView.as_view()),
        name='detalle_aprobada'
    ),

    path(
        route='editar_aprobada/<uuid:pk>/',
        view=login_required(AprobadaUpdateView.as_view()),
        name='editar_aprobada'
    ),

    path(
        route='preparadas/',
        view=login_required(PreparadasListView.as_view()),
        name='listar_preparadas'
    ),

    path(
        route='detalle_preparada/<uuid:pk>/',
        view=login_required(PreparadaDetailView.as_view()),
        name='detalle_preparada'
    ),

    path(
        route='editar_preparada/<uuid:pk>/',
        view=login_required(PreparadaUpdateView.as_view()),
        name='editar_preparada'
    ),

    path(
        route='listar_listasenviar/',
        view=login_required(ListasEnviarListView.as_view()),
        name='listar_listasenviar'
    ),

    path(
        route='enviar_listasenviar/<uuid:lista_id>/',
        view=login_required(ListasEnviarView.as_view()),
        name='enviar_listasenviar'
    ),

    path(
        route='detalle_listaenviar/<uuid:pk>/',
        view=login_required(ListaEnviarDetailView.as_view()),
        name='detalle_listaenviar'
    ),

    path(
        route='enviadas/',
        view=login_required(EnviadaListView.as_view()),
        name='listar_enviadas'
    ),

    path(
        route='detalle_enviada/<uuid:pk>/',
        view=login_required(EnviadaDetailView.as_view()),
        name='detalle_enviada'
    ),

    path(
        route='editar_enviada/<uuid:pk>/',
        view=login_required(EnviadaUpdateView.as_view()),
        name='editar_enviada'
    ),

    path(
        route='terminadas/',
        view=login_required(TerminadaListView.as_view()),
        name='listar_terminadas'
    ),

    path(
        route='detalle_terminada/<uuid:pk>/',
        view=login_required(TerminadaDetailView.as_view()),
        name='detalle_terminada'
    ),

    path(
        route='obtener_peritos/<uuid:aseguradora_id>/',
        view=login_required(ObtenerPeritosView.as_view()),
        name='obtener_peritos'
    )

]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('apps.users.urls'), namespace='auth')),
    path('', include(('apps.seguros.urls'), namespace='seguros'))
]

# Configuración para servir archivos de medios durante el desarrollo
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/pages/preparadas/editar_preparada.html
{% extends "includes/base/base.html" %}

{% load humanize %}

{% block contenido %}
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ header_page }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href={% url "seguros:listar_licitaciones" %}>Home</a></li>
              <li class="breadcrumb-item active"><a href={{list_url}}>{{ header_page }}</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">{{card_title}}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="POST" name="form" id="id_form">
              {% csrf_token %}

              <input type="hidden" name='accion' value={{accion}}>
              <div class="card-header">
                <div class="row">

                    <div class="card card-primary w-100">
                      <div class="card-header">
                        <h3 class="card-title">Operación</h3>
                        <div class="card-tools">
                          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                          </button>
                        </div>
                        <!-- /.card-tools -->
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body">

                        <div class="row">

                          <div class="col-md-3 col-xl-2">
                            <div class="col-md-12">
                              <div class="form-group">
                                <label for="inputCantidadArticulosListos">Artículos Listos</label>
                                <input type="number" class="form-control" step="any" maxlength="4" name={{form.cantidad_articulos_listos.name}} value={{form.cantidad_articulos_listos.value}} >
                              </div>
                            </div>

                            <div class="col-md-12">
                              <div class="form-group">
                                <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                  {{ form.terminado }}
                                  <label class="custom-control-label" for="customSwitch3">Lista Enviar</label>
                                </div>
                              </div>
                            </div>
                          </div>

                          <div class="col-md-9 col-xl-10">
                            <div class="form-group">
                              <label for="inputComentario">Comentario</label>
                              {{form.comentario}}
                            </div>
                          </div>

                        </div>
                          
                      </div>
                      <!-- /.card-body -->
                    </div>

                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="id_enviar">
                  {% if accion == 'agregar' %}
                    Crear
                  {% else %}
                    Guardar Cambios
                  {% endif %}
                </button>
                <a href={{ list_url }} class="btn btn-info">Cancelar</a>
              </div>
            </form>
          </div>
          <!-- /.card -->
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock contenido %}

{% block script %}
  <script type="application/javascript">
    $(function () {

      {% if form.errors %}
        let errors = '';
        {% for field in form %}
          {% for error in field.errors %}
            errors += '{{ error }}\n';
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          errors += '{{ error }}\n';
        {% endfor %}
        Swal.fire({
          title: 'Error!',
          text: errors,
          icon: 'error'
        });
      {% endif %}

      $('form').on('submit', function (e) {
        e.preventDefault();
        let parameters = $(this).serializeArray();
        $.ajax({
          url: window.location.pathname,
          type: 'POST',
          data: parameters,
          dataType: 'json'
        }).done(function (data) {
          if (!data.hasOwnProperty('error')) {
            // Si no hay errores generales, redirigir
            location.href = '{{ list_url }}';
            return false;
          }
      
          // Si hay errores generales, mostrarlos
          alerta_error(data.error);

          // Si hay errores del formulario, mostrarlos también
          if (data.hasOwnProperty('form_errors')) {
            let formErrors = '';
            for (let error in data.form_errors) {
              formErrors += data.form_errors[error].join('\n');
            }
            Swal.fire({
              title: 'Error en el formulario',
              text: formErrors,
              icon: 'error'
            });
          }
        }).fail(function (jqXHR, textStatus, errorThrown) {
          alerta_error(textStatus + ': ' + errorThrown);
        }).always(function (data) {

        });
      });

      document.querySelector('[name="cantidad_articulos_listos"]').addEventListener('change', function(event) {
        let CantidadArticulosInput = event.target;
        let valor = CantidadArticulosInput.value;

        if (!/^\d+$/.test(valor) || valor.length > 4) {
            alerta_error('Artículos Listos debe ser un número positivo de no más de 4 dígitos');
            CantidadArticulosInput.value = '';
            CantidadArticulosInput.focus();
        }
      });

      $(document).ready(function(){
        // Desactiva las flechas en todos los campos de número
        $('input[type="number"]').on('keydown', function(e) {
            if (e.which === 38 || e.which === 40) {
                e.preventDefault();
            }
        });
      });

      document.querySelector('[name="terminado"]').addEventListener('change', function(event) {
        var terminadoInput = event.target;
        var cantidadArticulosListoInput = document.querySelector('[name="cantidad_articulos_listos"]');
        var comentarioInput = document.querySelector('[name="comentario"]');
        var cantidadArticulosListo = parseInt(cantidadArticulosListoInput.value);
        var articulos = parseInt('{{ articulos }}');
        
        if (terminadoInput.checked && (cantidadArticulosListo !== articulos && cantidadArticulosListo <= 0 || comentarioInput.value === '')) {
            alerta_error('Para cambiar "Lista Enviar", "Artículos Listos" debe ser igual a ' + articulos + '. Si desea enviar con faltante, agregue un comentario.');
            terminadoInput.checked = false;
        }
      });

    });
  </script>
{% endblock script %}

templates/pages/preparadas/listar_preparadas.html
{% extends "includes/componentes/listado.html" %}

{% load humanize %}

{% block columnas %}
    <tr>
        <th>Fecha Aprobada</th>
        <th>Siniestro</th>
        <th>Monto</th>
        <th>Localidad</th>
        <th>Seguro</th>
        <th>Art.</th>
        <th>Art. Listos</th>
        <th>Días Disponibles</th>

        <th>Acciones</th>
    </tr>
{% endblock columnas %}

{% block filas %}
    {% for preparada in preparadas %}
    <tr>

        <td>
            {% if preparada.aprobada.fecha_aprobado %}
                {{ preparada.aprobada.fecha_aprobado|date:'d/m/Y' }}
            {% endif %}
        </td>

        <td>
            {% if preparada.aprobada.licitacion.numero_siniestro %}
                {{ preparada.aprobada.licitacion.numero_siniestro }}
            {% endif %}
        </td>

        <td>
            {% if preparada.aprobada.licitacion.monto %}
                {{ preparada.aprobada.licitacion.monto }}
            {% endif %}
        </td>

        <td>
            {% if preparada.aprobada.licitacion.datos_entrega.localidad %}
                {{ preparada.aprobada.licitacion.datos_entrega.localidad }} - 
                {{ preparada.aprobada.licitacion.datos_entrega.localidad.provincia }}
            {% endif %}
        </td>

        <td>
            {% if preparada.aprobada.licitacion.aseguradora %}
                {{ preparada.aprobada.licitacion.aseguradora }}
            {% endif %}
        </td>

        <td>
            {% if preparada.aprobada.licitacion.cantidad_articulos %}
                {{ preparada.aprobada.licitacion.cantidad_articulos }}
            {% endif %}
        </td>

        <td>
            {% if preparada.cantidad_articulos_listos %}
                {{ preparada.cantidad_articulos_listos }}
            {% endif %}
        </td>

        <td>
            {{ preparada.dias_restantes|default:"No disponible" }}
        </td>

        <td class="project-actions text-right">
            <a class="btn btn-primary btn-sm" href={% url "seguros:detalle_preparada" preparada.id %}>
                <i class="fas fa-folder">
                </i>
                Ver
            </a>
            {% with first_group=request.user.groups.all|first %}
                {% if request.user == preparada.aprobada.licitacion.user or first_group.name == 'GERENTE_GENERAL' or first_group.name == 'GERENTE_SUCURSAL' and request.user.perfil.sucursal == preparada.aprobada.licitacion.sucursal or first_group.name == 'SUPERVISOR' and request.user.perfil.sucursal == preparada.aprobada.licitacion.sucursal %}
                <a class="btn btn-warning btn-sm" href={% url "seguros:editar_preparada" preparada.id %}>
                    <i class="fas fa-pencil-alt">
                    </i>
                    Editar
                </a>
                {% endif %}
            {% endwith %}
        </td>
    </tr>
    {% endfor %}
{% endblock filas %}