apps/seguros/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import Inicio, LicitacionDetailView, LicitacionesListView, AprobadasListView, AprobadaDetailView, AprobadaUpdateView, EnviadaListView, EnviadaDetailView, EnviadaUpdateView, LicitacionCreateView, LicitacionUpdateView, LicitacionDeleteView, ListasEnviarListView, ListasEnviarView, ListaEnviarDetailView, PreparadasListView, PreparadaDetailView, PreparadaUpdateView, ObtenerPeritosView, TerminadaListView, TerminadaDetailView

app_name = 'apps.seguros'

urlpatterns = [

    path(
        route='',
        view=login_required(Inicio.as_view()),
        name='inicio'
    ),

    path(
        route='licitaciones/',
        view=login_required(LicitacionesListView.as_view()),
        name='listar_licitaciones'
    ),

    path(
        route='crear_licitacion/',
        view=login_required(LicitacionCreateView.as_view()),
        name='crear_licitacion'
    ),

    path(
        route='detalle_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDetailView.as_view()),
        name='detalle_licitacion'
    ),

    path(
        route='editar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionUpdateView.as_view()),
        name='editar_licitacion'
    ),

    path(
        route='eliminar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDeleteView.as_view()),
        name='eliminar_licitacion'
    ),

    path(
        route='aprobadas/',
        view=login_required(AprobadasListView.as_view()),
        name='listar_aprobadas'
    ),

    path(
        route='detalle_aprobada/<uuid:pk>/',
        view=login_required(AprobadaDetailView.as_view()),
        name='detalle_aprobada'
    ),

    path(
        route='editar_aprobada/<uuid:pk>/',
        view=login_required(AprobadaUpdateView.as_view()),
        name='editar_aprobada'
    ),

    path(
        route='preparadas/',
        view=login_required(PreparadasListView.as_view()),
        name='listar_preparadas'
    ),

    path(
        route='detalle_preparada/<uuid:pk>/',
        view=login_required(PreparadaDetailView.as_view()),
        name='detalle_preparada'
    ),

    path(
        route='editar_preparada/<uuid:pk>/',
        view=login_required(PreparadaUpdateView.as_view()),
        name='editar_preparada'
    ),

    path(
        route='listar_listasenviar/',
        view=login_required(ListasEnviarListView.as_view()),
        name='listar_listasenviar'
    ),

    path(
        route='enviar_listasenviar/<uuid:lista_id>/',
        view=login_required(ListasEnviarView.as_view()),
        name='enviar_listasenviar'
    ),

    path(
        route='detalle_listaenviar/<uuid:pk>/',
        view=login_required(ListaEnviarDetailView.as_view()),
        name='detalle_listaenviar'
    ),

    path(
        route='enviadas/',
        view=login_required(EnviadaListView.as_view()),
        name='listar_enviadas'
    ),

    path(
        route='detalle_enviada/<uuid:pk>/',
        view=login_required(EnviadaDetailView.as_view()),
        name='detalle_enviada'
    ),

    path(
        route='editar_enviada/<uuid:pk>/',
        view=login_required(EnviadaUpdateView.as_view()),
        name='editar_enviada'
    ),

    path(
        route='terminadas/',
        view=login_required(TerminadaListView.as_view()),
        name='listar_terminadas'
    ),

    path(
        route='detalle_terminada/<uuid:pk>/',
        view=login_required(TerminadaDetailView.as_view()),
        name='detalle_terminada'
    ),

    path(
        route='obtener_peritos/<uuid:aseguradora_id>/',
        view=login_required(ObtenerPeritosView.as_view()),
        name='obtener_peritos'
    )

]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('apps.users.urls'), namespace='auth')),
    path('', include(('apps.seguros.urls'), namespace='seguros'))
]

# Configuración para servir archivos de medios durante el desarrollo
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/pages/licitaciones/detalle_licitacion.html
{% extends "includes/base/base.html" %}

{% load humanize %}

{% block contenido %}

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{ header_page }}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href={% url "seguros:listar_licitaciones" %}>Home</a></li>
            <li class="breadcrumb-item active"><a href={{list_url}}>{{ header_page }}</a></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        
        <!-- general form elements -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">{{card_title}}</h3>
          </div>
          <!-- /.card-header -->
        
          <div class="card-body">
            <div class="row">

              <!-- left column -->
              <div class="col-md-4">
                <div class="col-md-12">
                  <div class="card card-primary">
                    <div class="card-header">
                      <h3 class="card-title">Presupuesto</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                        </button>
                      </div>
                      <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      
                      <div class="row">
                        <div class="col-lg-12">
                          <div class="form-group">
                            <label for="inputPresupuesto">N° Presupuesto</label>
                            <input type="text" class="form-control" value="{{licitacion.numero_presupuesto}}" disabled>
                          </div>
                        </div>

                        <div class="col-lg-6">
                          <div class="form-group">
                            <label for="inputMonto">Monto</label>
                            <input type="text" class="form-control" value="{{licitacion.monto}}" disabled>
                          </div>                          
                        </div>

                        <div class="col-lg-6">
                          <div class="form-group">
                            <label for="inputDemora">Demora</label>
                            <input type="text" class="form-control" value="{{licitacion.demora}}" disabled>
                          </div>
                        </div>

                        <div class="col-lg-4">
                          <div class="form-group">
                            <label for="inputCantidadArticulos">Artículos</label>
                            <input type="text" class="form-control" value="{{licitacion.cantidad_articulos}}" disabled>
                          </div>
                        </div>

                        <div class="col-lg-8">
                          <div class="form-group">
                            <label for="inputPerito">Costo Transporte</label>
                            <input type="text" class="form-control" value="{{licitacion.costo_transporte }}" disabled>
                          </div>
                        </div>

                      </div>                        
                    </div>
                    <!-- /.card-body -->
                  </div>
                </div>
              </div>

              <!-- center column -->
              <div class="col-md-4">
                <div class="col-md-12">
                  <div class="card card-primary">
                    <div class="card-header">
                      <h3 class="card-title">Seguro</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                        </button>
                      </div>
                      <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      
                      <div class="row">
                        <div class="col-xl-12">
                          <div class="form-group">
                            <label for="inputSiniestro">N° Siniestro</label>
                            <input type="text" class="form-control" value="{{licitacion.numero_siniestro}}" disabled>
                          </div>
                        </div>

                        <div class="col-xl-6">
                          <div class="form-group">
                            <label for="inputAseguradora">Aseguradora</label>
                            <input type="text" class="form-control" value="{{licitacion.aseguradora}}" disabled>
                          </div>
                        </div>
                        
                        <div class="col-xl-6">
                          <div class="form-group">
                            <label for="inputPerito">Perito</label>
                            <input type="text" class="form-control" 
                            value=
                            {% if licitacion.perito %}
                                "{{licitacion.perito}}" 
                            {% else %}
                                ""
                            {% endif %}
                            disabled>
                          </div>
                        </div>

                      </div>

                    </div>
                    <!-- /.card-body -->
                  </div>
                </div>
              </div>

              <!-- rigth column -->
              <div class="col-md-4">
                <div class="col-md-12">
                  <div class="card card-primary">
                    <div class="card-header">
                      <h3 class="card-title">Vehículo</h3>
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                        </button>
                      </div>
                      <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col-lg-6">
                          <div class="form-group">
                            <label for="inputVehiculo">Vehículo</label>
                            <input type="text" class="form-control" value="{{licitacion.vehiculo}}" disabled>
                          </div>
                        </div>
                        
                        <div class="col-lg-6">
                          <div class="form-group">
                            <label for="inputDominio">Dominio</label>
                            <input type="text" class="form-control" value="{{licitacion.dominio}}" disabled>
                          </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-xl-6">
                          <div class="form-group">
                            <label for="inputProvincia">Provincia</label>
                            <input type="text" class="form-control" value="{{licitacion.datos_entrega.localidad.provincia}}" disabled>
                          </div>
                        </div>
                        
                        <div class="col-xl-6">
                          <div class="form-group">
                            <label for="inputLocalidad">Localidad</label>
                            <input type="text" class="form-control" value="{{licitacion.datos_entrega.localidad}}" disabled>
                          </div>
                        </div>
                      </div>
                        
                    </div>
                    <!-- /.card-body -->
                  </div>

                    <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Aprobado</h3>
                        <div class="card-tools">
                          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                          </button>
                        </div>
                        <!-- /.card-tools -->
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body">
                        <div class="row">
                          <div class="col-6">

                            <div class="form-group">
                              <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                <input type="checkbox" class="custom-control-input" id="customSwitch3" disabled
                                {% if licitacion.terminado %}checked{% endif %}
                                >
                                <label class="custom-control-label" for="customSwitch3">Aprobada</label>
                                </div>
                            </div>
                          </div>
                        </div>      
                      </div>
                      <!-- /.card-body -->
                    </div>

                </div>
              </div>

            </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <a href={{ list_url }} class="btn btn-info btn-sm">Volver</a>
            
            {% with first_group=request.user.groups.all|first %}
              {% if request.user == licitacion.user or first_group.name == 'GERENTE_GENERAL' or first_group.name == 'GERENTE_SUCURSAL' and request.user.perfil.sucursal == licitacion.sucursal or first_group.name == 'SUPERVISOR' and request.user.perfil.sucursal == licitacion.sucursal %}
                <a class="btn btn-warning btn-sm" href={% url "seguros:editar_licitacion" licitacion.id %}>
                  <i class="fas fa-pencil-alt">
                  </i>
                  Editar
                </a>
              {% endif %}
            {% endwith %}
          </div>
          <!-- /.card-footer -->

        </div>

        </div>

      </div>
    </div>
  </section>

{% endblock contenido %}

templates/pages/licitaciones/eliminar_licitacion.html
{% extends "includes/base/base.html" %}

{% load humanize %}

{% block contenido %}
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ header_page }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href={% url "seguros:listar_licitaciones" %}>Home</a></li>
              <li class="breadcrumb-item active"><a href={{list_url}}>{{ header_page }}</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">{{card_title}}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="POST">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger alert-dismissible">
                        <h5><i class="icon fas fa-ban">Notificación</i></h5>
                        ¿Estás seguro de eliminar la Licitación N°: {{object.numero_siniestro}}
                    </div>
                </div>  
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Si, eliminar</button>
                <a href={{ list_url }} class="btn btn-info">Cancelar</a>
              </div>
            </form>
          </div>
          <!-- /.card -->
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock contenido %}

{% block script %}
  <script type="application/javascript">
    $(function () {

      $('form').on('submit', function (e) {
        e.preventDefault();
        let parameters = $(this).serializeArray();
        $.ajax({
          url: window.location.pathname,
          type: 'POST',
          data: parameters,
          dataType: 'json'
        }).done(function (data) {
          if(!data.hasOwnProperty('error')) {
            location.href = '{{ list_url }}';
            return false;
          }
          alerta_error(data.error);
        }).fail(function (jqXHR, textStatus, errorThrown) {
          alert(textStatus + ': ' + errorThrown);
        }).always(function (data) {
          
        });
      });
    });
  </script>
{% endblock script %}

templates/pages/licitaciones/listar_licitaciones.html
{% extends "includes/componentes/listado.html" %}

{% load static %}
{% load humanize %}

{% block columnas %}
    <tr>
        <th>Fecha</th>
        <th>Vehículo</th>
        <th>Dominio</th>
        <th>Presupuesto</th>
        <th>Seguro</th>
        <th>Siniestro</th>
        <th>Monto</th>
        <th>Localidad</th>
        <th>Usuario</th>
        <th>Sucursal</th>
        <th>Acciones</th>
    </tr>
{% endblock columnas %}

{% block filas %}
    {% for licitacion in licitaciones %}
    <tr>
            <td>
                {% if licitacion.creado %}
                    {{ licitacion.creado|date:'d/m/Y' }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.vehiculo %}
                    {{ licitacion.vehiculo|upper }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.dominio %}
                    {{ licitacion.dominio|upper }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.numero_presupuesto %}
                    {{ licitacion.numero_presupuesto }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.aseguradora %}
                    {{ licitacion.aseguradora }}
                {% endif %}
            </td>
            
            <td>
                {% if licitacion.numero_siniestro %}
                    {{ licitacion.numero_siniestro }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.monto %}
                    ${{ licitacion.monto|floatformat:2|intcomma }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.datos_entrega.localidad %}
                    {{ licitacion.datos_entrega.localidad }}
                {% endif %}
            </td>

            <td>
                {{ licitacion.user.first_name }}
            </td>

            <td>
                {% if licitacion.sucursal %}
                    {{ licitacion.sucursal }}
                {% endif %}
            </td>

        <td class="project-actions text-right">
            <a class="btn btn-primary btn-sm" href={% url "seguros:detalle_licitacion" licitacion.id %}>
                <i class="fas fa-folder">
                </i>
                Ver
            </a>

            {% with first_group=request.user.groups.all|first %}
                {% if request.user == licitacion.user or first_group.name == 'GERENTE_GENERAL' or first_group.name == 'GERENTE_SUCURSAL' and request.user.perfil.sucursal == licitacion.sucursal or first_group.name == 'SUPERVISOR' and request.user.perfil.sucursal == licitacion.sucursal %}
                
                    <a class="btn btn-warning btn-sm" href={% url "seguros:editar_licitacion" licitacion.id %}>
                        <i class="fas fa-pencil-alt">
                        </i>
                        Editar
                    </a>

                    <a class="btn btn-danger btn-sm" href={% url "seguros:eliminar_licitacion" licitacion.id %}>
                        <i class="fas fa-trash">
                        </i>
                        Borrar
                    </a>

                {% endif %}
            {% endwith %}

        </td>
    </tr>
    {% endfor %}
{% endblock filas %}

templates/pages/licitaciones/listar_licitaciones_AJAX.html
{% extends "includes/componentes/listado.html" %}

{% load static %}
{% load humanize %}

{% block columnas %}
    <tr>
        <th>Fecha</th>
        <th>Vehículo</th>
        <th>Dominio</th>
        <th>Presupuesto</th>
        <th>Seguro</th>
        <th>Siniestro</th>
        <th>Monto</th>
        <th>Localidad</th>
        <th>Usuario</th>
        <th>Sucursal</th>
        <th>Acciones</th>
    </tr>
{% endblock columnas %}

{% block filas %}
    {% comment %} {% for licitacion in licitaciones %}
    <tr>                        
            <td>
                {% if licitacion.creado %}
                    {{ licitacion.creado|date:'d/m/Y' }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.vehiculo %}
                    {{ licitacion.vehiculo|upper }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.dominio %}
                    {{ licitacion.dominio|upper }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.numero_presupuesto %}
                    {{ licitacion.numero_presupuesto }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.aseguradora %}
                    {{ licitacion.aseguradora }}
                {% endif %}
            </td>
            
            <td>
                {% if licitacion.numero_siniestro %}
                    {{ licitacion.numero_siniestro }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.monto %}
                    $ {{ licitacion.monto|floatformat:2|intcomma }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.localidad %}
                    {{ licitacion.localidad }}
                {% endif %}
            </td>

            <td class="py-1">
                {% if user.perfil.imagen and user.perfil.imagen.url %}
                    <img src={{ user.perfil.imagen.url }} alt="image" />
                    {{ user }}
                {% else %}
                    {{ user }}
                {% endif %}
            </td>

            <td>
                {% if licitacion.sucursal %}
                    {{ licitacion.sucursal }}
                {% endif %}
            </td>

        <td class="project-actions text-right">
            <a class="btn btn-primary btn-sm" href="#">
                <i class="fas fa-folder">
                </i>
                Ver
            </a>
            <a class="btn btn-warning btn-sm" href={% url "seguros:editar_licitacion" licitacion.id %}>
                <i class="fas fa-pencil-alt">
                </i>
                Editar
            </a>
            <a class="btn btn-danger btn-sm" href={% url "seguros:eliminar_licitacion" licitacion.id %}>
                <i class="fas fa-trash">
                </i>
                Borrar
            </a>
        </td>
    </tr>
    {% endfor %} {% endcomment %}
{% endblock filas %}
{% block script %}
<script src={% static "js/licitacion.js" %}></script>
{% endblock script %}