apps/seguros/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import Inicio, LicitacionDetailView, LicitacionesListView, AprobadasListView, AprobadaDetailView, AprobadaUpdateView, EnviadaListView, EnviadaDetailView, EnviadaUpdateView, LicitacionCreateView, LicitacionUpdateView, LicitacionDeleteView, ListasEnviarListView, ListasEnviarView, ListaEnviarDetailView, PreparadasListView, PreparadaDetailView, PreparadaUpdateView, ObtenerPeritosView, TerminadaListView, TerminadaDetailView

app_name = 'apps.seguros'

urlpatterns = [

    path(
        route='',
        view=login_required(Inicio.as_view()),
        name='inicio'
    ),

    path(
        route='licitaciones/',
        view=login_required(LicitacionesListView.as_view()),
        name='listar_licitaciones'
    ),

    path(
        route='crear_licitacion/',
        view=login_required(LicitacionCreateView.as_view()),
        name='crear_licitacion'
    ),

    path(
        route='detalle_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDetailView.as_view()),
        name='detalle_licitacion'
    ),

    path(
        route='editar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionUpdateView.as_view()),
        name='editar_licitacion'
    ),

    path(
        route='eliminar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDeleteView.as_view()),
        name='eliminar_licitacion'
    ),

    path(
        route='aprobadas/',
        view=login_required(AprobadasListView.as_view()),
        name='listar_aprobadas'
    ),

    path(
        route='detalle_aprobada/<uuid:pk>/',
        view=login_required(AprobadaDetailView.as_view()),
        name='detalle_aprobada'
    ),

    path(
        route='editar_aprobada/<uuid:pk>/',
        view=login_required(AprobadaUpdateView.as_view()),
        name='editar_aprobada'
    ),

    path(
        route='preparadas/',
        view=login_required(PreparadasListView.as_view()),
        name='listar_preparadas'
    ),

    path(
        route='detalle_preparada/<uuid:pk>/',
        view=login_required(PreparadaDetailView.as_view()),
        name='detalle_preparada'
    ),

    path(
        route='editar_preparada/<uuid:pk>/',
        view=login_required(PreparadaUpdateView.as_view()),
        name='editar_preparada'
    ),

    path(
        route='listar_listasenviar/',
        view=login_required(ListasEnviarListView.as_view()),
        name='listar_listasenviar'
    ),

    path(
        route='enviar_listasenviar/<uuid:lista_id>/',
        view=login_required(ListasEnviarView.as_view()),
        name='enviar_listasenviar'
    ),

    path(
        route='detalle_listaenviar/<uuid:pk>/',
        view=login_required(ListaEnviarDetailView.as_view()),
        name='detalle_listaenviar'
    ),

    path(
        route='enviadas/',
        view=login_required(EnviadaListView.as_view()),
        name='listar_enviadas'
    ),

    path(
        route='detalle_enviada/<uuid:pk>/',
        view=login_required(EnviadaDetailView.as_view()),
        name='detalle_enviada'
    ),

    path(
        route='editar_enviada/<uuid:pk>/',
        view=login_required(EnviadaUpdateView.as_view()),
        name='editar_enviada'
    ),

    path(
        route='terminadas/',
        view=login_required(TerminadaListView.as_view()),
        name='listar_terminadas'
    ),

    path(
        route='detalle_terminada/<uuid:pk>/',
        view=login_required(TerminadaDetailView.as_view()),
        name='detalle_terminada'
    ),

    path(
        route='obtener_peritos/<uuid:aseguradora_id>/',
        view=login_required(ObtenerPeritosView.as_view()),
        name='obtener_peritos'
    )

]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('apps.users.urls'), namespace='auth')),
    path('', include(('apps.seguros.urls'), namespace='seguros'))
]

# Configuración para servir archivos de medios durante el desarrollo
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/pages/enviadas/editar_enviada.html
{% extends "includes/base/base.html" %}

{% load humanize %}

{% block contenido %}
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ header_page }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href={% url "seguros:listar_licitaciones" %}>Home</a></li>
              <li class="breadcrumb-item active"><a href={{list_url}}>{{ header_page }}</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">{{card_title}}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="POST" name="form" id="id_form" enctype="multipart/form-data">
              {% csrf_token %}

              <input type="hidden" name='accion' value={{accion}}>
              <div class="card-header">
                <div class="row">

                    <div class="card card-primary w-100">
                      <div class="card-header">
                        <h3 class="card-title">Info</h3>
                        <div class="card-tools">
                          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                          </button>
                        </div>
                        <!-- /.card-tools -->
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body">

                        <div class="row">

                          <div class="col-md-3 col-xl-2">
                            <div class="col-md-10">
                              <div class="form-group">
                                <label for="inputFactura">Factura</label>
                                {{form.factura}}
                              </div>
                            </div>
                          </div>

                          <div class="col-md-9 col-xl-10">
                            <div class="col-md-10">
                              <div class="form-group">
                                <label for="remito">Remito</label>
                                <div class="custom-file">
                                  <input type="file" class="custom-file-input" name="remito" accept="image/*" capture="camera">
                                  <label class="custom-file-label" for="exampleInputFile">Seleccione imagen</label>
                                </div>                  
                              </div>
                            </div>
                          </div>

                        </div>
                          
                      </div>
                      <!-- /.card-body -->
                    </div>

                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="id_enviar">
                    Guardar Cambios
                </button>
                <a href={{ list_url }} class="btn btn-info">Cancelar</a>
              </div>
            </form>
          </div>
          <!-- /.card -->
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock contenido %}

{% block script %}
  <script type="application/javascript">
    $(function () {

      {% if form.errors %}
        let errors = '';
        {% for field in form %}
          {% for error in field.errors %}
            errors += '{{ error }}\n';
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          errors += '{{ error }}\n';
        {% endfor %}
        Swal.fire({
          title: 'Error!',
          text: errors,
          icon: 'error'
        });
      {% endif %}

      $('form').on('submit', function (e) {
        e.preventDefault();
        let formData = new FormData(this);

        $.ajax({
          url: window.location.pathname,
          type: 'POST',
          data: formData,
          dataType: 'json',
          contentType: false,
          processData: false
        }).done(function (data) {
          if (!data.hasOwnProperty('error')) {
            // Si no hay errores generales, redirigir
            location.href = '{{ list_url }}';
            return false;
          }
      
          // Si hay errores generales, mostrarlos
          alerta_error(data.error);

          // Si hay errores del formulario, mostrarlos también
          if (data.hasOwnProperty('form_errors')) {
            let formErrors = '';
            for (let error in data.form_errors) {
              formErrors += data.form_errors[error].join('\n');
            }
            Swal.fire({
              title: 'Error en el formulario',
              text: formErrors,
              icon: 'error'
            });
          }
        }).fail(function (jqXHR, textStatus, errorThrown) {
          alerta_error(textStatus + ': ' + errorThrown);
        }).always(function (data) {

        });
      });
    });
  </script>
{% endblock script %}

templates/pages/enviadas/listar_enviadas.html
{% extends "includes/componentes/listado.html" %}

{% load static %}
{% load humanize %}

{% block columnas %}
    <tr>
        <th>Fecha Enviada</th>
        <th>Siniestro</th>
        <th>Localidad</th>
        <th>OC</th>
        <th>Factura</th>
        <th>Remito</th>
        <th>Usuario</th>
        <th>Sucursal</th>
        <th>Acciones</th>
    </tr>
{% endblock columnas %}

{% block filas %}
    {% for enviada in enviadas %}
    <tr>
            <td>
                {% if enviada.creado %}
                    {{ enviada.creado|date:'d/m/Y' }}
                {% endif %}
            </td>

            <td>
                {% if enviada.listaenviar.preparada.aprobada.licitacion.numero_siniestro %}
                    {{ enviada.listaenviar.preparada.aprobada.licitacion.numero_siniestro }}
                {% endif %}
            </td>

            <td>
                {% if enviada.listaenviar.preparada.aprobada.licitacion.datos_entrega.localidad %}
                    {{ enviada.listaenviar.preparada.aprobada.licitacion.datos_entrega.localidad }}
                {% endif %}
            </td>

            <td>
                {% if enviada.listaenviar.preparada.aprobada.numero_orden_compra %}
                    {{ enviada.listaenviar.preparada.aprobada.numero_orden_compra }}
                {% endif %}
            </td>

            <td>
                {% if enviada.factura %}
                    {{ enviada.factura }}
                {% endif %}
            </td>

            <td>
                <ul class="list-inline">
                    {% if enviada.remito %}
                        <li class="list-inline-item">
                            <a href={{enviada.remito.url}} download><img alt="remito" class="table-avatar" src="{{enviada.remito.url}}"></a>
                        </li>
                    {% endif %}
                </ul>
            </td>

            <td>
                {{ enviada.listaenviar.preparada.aprobada.licitacion.user.first_name }}
            </td>

            <td>
                {% if enviada.listaenviar.preparada.aprobada.licitacion.sucursal %}
                    {{ enviada.listaenviar.preparada.aprobada.licitacion.sucursal }}
                {% endif %}
            </td>

        <td class="project-actions text-right">
            <a class="btn btn-primary btn-sm" href={% url "seguros:detalle_enviada" enviada.id %}>
                <i class="fas fa-folder">
                </i>
                Ver
            </a>
            {% with first_group=request.user.groups.all|first %}
                {% if request.user == enviada.listaenviar.preparada.aprobada.licitacion.user or first_group.name == 'GERENTE_GENERAL' or first_group.name == 'GERENTE_SUCURSAL' and request.user.perfil.sucursal == enviada.listaenviar.preparada.aprobada.licitacion.sucursal or first_group.name == 'SUPERVISOR' and request.user.perfil.sucursal == enviada.listaenviar.preparada.aprobada.licitacion.sucursal %}
                <a class="btn btn-warning btn-sm" href={% url "seguros:editar_enviada" enviada.id %}>
                    <i class="fas fa-pencil-alt">
                    </i>
                    Editar
                </a>
                {% endif %}
            {% endwith %}
        </td>
    </tr>
    {% endfor %}
{% endblock filas %}