apps/seguros/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import Inicio, LicitacionDetailView, LicitacionesListView, AprobadasListView, AprobadaDetailView, AprobadaUpdateView, EnviadaListView, EnviadaDetailView, EnviadaUpdateView, LicitacionCreateView, LicitacionUpdateView, LicitacionDeleteView, ListasEnviarListView, ListasEnviarView, ListaEnviarDetailView, PreparadasListView, PreparadaDetailView, PreparadaUpdateView, ObtenerPeritosView, TerminadaListView, TerminadaDetailView

app_name = 'apps.seguros'

urlpatterns = [

    path(
        route='',
        view=login_required(Inicio.as_view()),
        name='inicio'
    ),

    path(
        route='licitaciones/',
        view=login_required(LicitacionesListView.as_view()),
        name='listar_licitaciones'
    ),

    path(
        route='crear_licitacion/',
        view=login_required(LicitacionCreateView.as_view()),
        name='crear_licitacion'
    ),

    path(
        route='detalle_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDetailView.as_view()),
        name='detalle_licitacion'
    ),

    path(
        route='editar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionUpdateView.as_view()),
        name='editar_licitacion'
    ),

    path(
        route='eliminar_licitacion/<uuid:pk>/',
        view=login_required(LicitacionDeleteView.as_view()),
        name='eliminar_licitacion'
    ),

    path(
        route='aprobadas/',
        view=login_required(AprobadasListView.as_view()),
        name='listar_aprobadas'
    ),

    path(
        route='detalle_aprobada/<uuid:pk>/',
        view=login_required(AprobadaDetailView.as_view()),
        name='detalle_aprobada'
    ),

    path(
        route='editar_aprobada/<uuid:pk>/',
        view=login_required(AprobadaUpdateView.as_view()),
        name='editar_aprobada'
    ),

    path(
        route='preparadas/',
        view=login_required(PreparadasListView.as_view()),
        name='listar_preparadas'
    ),

    path(
        route='detalle_preparada/<uuid:pk>/',
        view=login_required(PreparadaDetailView.as_view()),
        name='detalle_preparada'
    ),

    path(
        route='editar_preparada/<uuid:pk>/',
        view=login_required(PreparadaUpdateView.as_view()),
        name='editar_preparada'
    ),

    path(
        route='listar_listasenviar/',
        view=login_required(ListasEnviarListView.as_view()),
        name='listar_listasenviar'
    ),

    path(
        route='enviar_listasenviar/<uuid:lista_id>/',
        view=login_required(ListasEnviarView.as_view()),
        name='enviar_listasenviar'
    ),

    path(
        route='detalle_listaenviar/<uuid:pk>/',
        view=login_required(ListaEnviarDetailView.as_view()),
        name='detalle_listaenviar'
    ),

    path(
        route='enviadas/',
        view=login_required(EnviadaListView.as_view()),
        name='listar_enviadas'
    ),

    path(
        route='detalle_enviada/<uuid:pk>/',
        view=login_required(EnviadaDetailView.as_view()),
        name='detalle_enviada'
    ),

    path(
        route='editar_enviada/<uuid:pk>/',
        view=login_required(EnviadaUpdateView.as_view()),
        name='editar_enviada'
    ),

    path(
        route='terminadas/',
        view=login_required(TerminadaListView.as_view()),
        name='listar_terminadas'
    ),

    path(
        route='detalle_terminada/<uuid:pk>/',
        view=login_required(TerminadaDetailView.as_view()),
        name='detalle_terminada'
    ),

    path(
        route='obtener_peritos/<uuid:aseguradora_id>/',
        view=login_required(ObtenerPeritosView.as_view()),
        name='obtener_peritos'
    )

]

apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import UserDetailView, UserListView, LoginFormView, SalirView

app_name = 'apps.users'

urlpatterns = [

    # path(
    #     route='registro/',
    #     view=UserCreateView.as_view(),
    #     name='registro'
    # ),
    path(
        route='detalle/<uuid:pk>/',
        view=login_required(UserDetailView.as_view()),
        name='detalle'
    ),
    # path(
    #     route='editar/<int:pk>/',
    #     view=UserUpdateView.as_view(),
    #     name='editar'
    # ),
    path(
        route='listado/',
        view=login_required(UserListView.as_view()),
        name='listado'
    ),
    path(
        route='login/',
        view=LoginFormView.as_view(),
        name='login'
    ),
    path(
        route='salir/',
        view=login_required(SalirView.as_view()),
        name='salir'
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('apps.users.urls'), namespace='auth')),
    path('', include(('apps.seguros.urls'), namespace='seguros'))
]

# Configuración para servir archivos de medios durante el desarrollo
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/includes/base/aside.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href={% url "seguros:inicio" %} class="brand-link">
      <img src={% static "adminlte/img/AdminLTELogo.png" %} alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">SGL</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          {% if request.user.perfil.imagen and user.perfil.imagen.url %}
            <img src={{ user.perfil.imagen.url }} class="img-circle elevation-2" alt="User Image">
            {% else %}
            <img src={% static "adminlte/img/user2-160x160.jpg" %} class="img-circle elevation-2" alt="User Image">
          {% endif %}
        </div>
        <div class="info">

          <a href="#" class="d-block">{{ request.user.username|upper }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      {% comment %} <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> {% endcomment %}

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          
          {% comment %} <li class="nav-header">Estados</li> {% endcomment %}
          <li class="nav-item">
            <a href={% url "seguros:listar_licitaciones" %} class="nav-link">
              <i class="nav-icon fa fa-plus"></i>
              <p>
                Licitaciones
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url "seguros:listar_aprobadas" %} class="nav-link">
              <i class="nav-icon fa fa-check"></i>
              <p>
                Aprobadas
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url "seguros:listar_preparadas" %} class="nav-link">
              <i class="nav-icon fas fa-dolly"></i>
              <p>
                En Preparación
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url "seguros:listar_listasenviar" %} class="nav-link">
              <i class="nav-icon fa fa-cubes"></i>
              <p>
                Listo para enviar
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url "seguros:listar_enviadas" %} class="nav-link">
              <i class="nav-icon fa fa-truck"></i>
              <p>
                Enviadas
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url "seguros:listar_terminadas" %} class="nav-link">
              <i class="nav-icon fa fa-spinner"></i>
              <p>
                Terminadas
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/includes/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SGL</title>

        <!-- Google Font: Source Sans Pro -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
        <!-- Theme style -->
        <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
        <!-- overlayScrollbars -->
        <link rel="stylesheet" href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
        <!-- Sweetalert2 -->
        <link rel="stylesheet" href="{% static 'adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
        <!-- Datatables -->
        <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"/>
        <!-- Select2 -->
        <link rel="stylesheet" href="{% static 'adminlte/plugins/select2/css/select2.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}"/>
        {% block head %}{% endblock head %}
    </head>

    <body class="hold-transition sidebar-mini layout-fixed dark-mode sidebar-closed sidebar-collapse" data-panel-auto-height-mode="height">
        <div class="wrapper">

            <!-- Navbar -->
            {% include "includes/base/header.html" %}
            <!-- /.navbar -->

            <!-- Main Sidebar Container -->
            {% include "includes/base/aside.html" %}

            <!-- Content Wrapper. Contains page content -->
            {% block contenido %}{% endblock contenido %}
            <!-- /.content-wrapper -->

            <!-- Footer -->
            {% include "includes/base/footer.html" %}
            <!-- /.footer -->

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->

        <!-- Script -->
        <!-- jQuery -->
        <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
        $.widget.bridge('uibutton', $.ui.button)
        </script>
        <!-- Bootstrap 4 -->
        <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- overlayScrollbars -->
        <script src="{% static 'adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script src="{% static 'adminlte/js/adminlte.js' %}"></script>
        <!-- Sweetalert2 -->
        <script src="{% static 'adminlte/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
        <!-- Mis funciones -->
        <script src="{% static 'js/functions.js' %}"></script>
        <!-- Datatables -->
        <script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.js' %}"></script>
        <script src="{% static 'adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
        <!-- Select2 -->
        <script src="{% static 'adminlte/plugins/select2/js/select2.min.js' %}"></script>
        <script src="{% static 'adminlte/plugins/select2/js/i18n/es.js' %}"></script>
        {% block script %}{% endblock script %}
        <!-- ./script -->

    </body>
</html>

templates/includes/base/base_detalle.html
{% extends "includes/base/base.html" %}

{% load humanize %}

{% block contenido %}

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{ header_page }}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href={% url "seguros:listar_licitaciones" %}>Home</a></li>
            <li class="breadcrumb-item active"><a href={{list_url}}>{{ header_page }}</a></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        
        <!-- general form elements -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">{{card_title}}</h3>
          </div>
          <!-- /.card-header -->
        
          <div class="card-body">
            <div class="row">



              

            </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <a href={{ list_url }} class="btn btn-info btn-sm">Volver</a>
            <a class="btn btn-warning btn-sm" href={% url "seguros:editar_licitacion" licitacion.id %}>
              <i class="fas fa-pencil-alt">
              </i>
              Editar
            </a>
          </div>
          <!-- /.card-footer -->

        </div>

        </div>

      </div>
    </div>
  </section>

{% endblock contenido %}

templates/includes/base/footer.html
{% load static %}

<footer class="main-footer dark-mode">
    <strong>Copyright &copy; 2024 <a href="https://derkayvargas.com" target=_blank>Derka y Vargas S.A.</a></strong>
    Todos los derechos reservados.
    <div class="float-right d-none d-sm-inline-block">
      <b>admin</b> Miguel Puente
    </div>
</footer>

templates/includes/base/header.html
{% load static %}

<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      {% comment %} <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li> {% endcomment %}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      {% comment %} <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li> {% endcomment %}

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src={% static "adminlte/img/user1-128x128.jpg" %} alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src={% static "adminlte/img/user8-128x128.jpg" %} alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src={% static "adminlte/img/user3-128x128.jpg" %} alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "auth:salir" %} role="button">
          <i class="fas fa-power-off"></i>
        </a>
      </li>
      {% comment %} <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> {% endcomment %}
    </ul>
  </nav>